version: 0.2

env:
    variables:
        S3_BUCKET: "alexazhu.com"
        APP_NAME: "alexazhu-personal-site"
        BUILD_ENV: "prod"

phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli

    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}

    post_build:
        commands:
            # Clear S3 bucket.
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - echo S3 bucket is cleared.

            # Copy main build artifacts
            - aws s3 cp dist/${APP_NAME} s3://${S3_BUCKET}/ --recursive

            # Copy new tab directly into assets
            - aws s3 cp $CODEBUILD_SRC_DIR_new_tab s3://${S3_BUCKET}/assets/new-tab/ --recursive

            # Copy resume pdf only
            - aws s3 cp $CODEBUILD_SRC_DIR_resume/Resume.pdf s3://${S3_BUCKET}/assets/resume/Resume.pdf

            # Copy 538-flipping README only
            - aws s3 cp $CODEBUILD_SRC_DIR_flipping/README.md s3://${S3_BUCKET}/assets/538-flipping/README.md

            - echo Build completed on `date`